# Generated by Django 5.2.3 on 2025-08-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blablabla',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
