# Generated by Django 5.2.3 on 2025-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_userprofile_blablabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blablabla',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='change_username_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
