# Generated by Django 5.2.3 on 2025-08-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_userprofile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='test',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
