# Generated by Django 5.2.3 on 2025-08-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_userprofile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test',
        ),
    ]
