# Generated by Django 5.2.3 on 2025-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_remove_userprofile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='change_username_data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
