# Generated by Django 5.2.3 on 2025-08-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_alter_userprofile_change_username_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='change_username_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
