# Generated by Django 5.2.3 on 2025-08-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_userprofile_change_username_data_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='change_username_data_two',
        ),
    ]
