# Generated by Django 5.2.3 on 2025-08-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_alter_userprofile_change_username_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='change_username_data',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
