# Generated by Django 5.2.3 on 2025-08-23 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_alter_userprofile_change_username_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='change_username_data',
            field=models.DateTimeField(blank=True, default=datetime.timedelta(microseconds=1), null=True),
        ),
    ]
